export const data = [
  "Frontend Developer",
  "NextJS",
  "Server Side & Client Side Rendering",
  "ReactJS",
  "React Testing Library",
  "React Context API",
  "Redux",
  "Javascript",
  "es6",
  "Html5",
  "css3",
  "Material-ui",
  "Ant Design",
  "Boostrap",
  "RESTful APIs",
  "GitLab",
  "unix",
  "Laravel",
  "PHP",
  "jQuery",
  "React Native",
  "Mobile Developer",
];
